AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Ec2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
      - Key: Name
        Value: inoue-vpc
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: inoue-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: inoue-route
  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref FrontendRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  FrontendSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-west-2a
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: inoue-public-1
  FrontendSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnet
      RouteTableId: !Ref FrontendRouteTable
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: 
    - VPC
    - IAMPolicy
    Properties:
      GroupDescription: "inoue handson sample"
      GroupName: "inoue-ap-sg"
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
      SecurityGroupIngress:
        - CidrIp: 103.79.12.129/32
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 103.79.12.129/32
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 113.147.91.142/32
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 113.147.91.142/32
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      Tags: 
        - Key: Name
          Value: inoue-ap-sg
      VpcId: !Ref VPC
  EC2:
    Type: AWS::EC2::Instance
    DependsOn: SecurityGroup
    Properties:
      AvailabilityZone: us-west-2a
      InstanceType: "t2.micro"
      KeyName: inoue
      ImageId: !Ref Ec2ImageId
      SecurityGroupIds: 
      - !Ref SecurityGroup
      SubnetId: !Ref FrontendSubnet
      Tags:
      - Key: Name
        Value: inoue-ap
      UserData: "IyEvYmluL2Jhc2gKCmF3cyBzMyBjcCBzMzovL2lub3VlLWFydGlmYWN0cy9oZWxsby1zZXJ2ZXIudGd6IC4vCnRhciB6eHZmIGhlbGxvLXNlcnZlci50Z3oKbXYgaGVsbG8tc2VydmVyIC91c3IvbG9jYWwvYmluLwptdiBoZWxsby1zZXJ2ZXIuc2VydmljZSAvZXRjL3N5c3RlbWQvc3lzdGVtLwoKc3lzdGVtY3RsIGRhZW1vbi1yZWxvYWQKc3lzdGVtY3RsIGVuYWJsZSBoZWxsby1zZXJ2ZXIuc2VydmljZQpzeXN0ZW1jdGwgc3RhcnQgaGVsbG8tc2VydmVyLnNlcnZpY2UK"
      IamInstanceProfile: 
        Name: !Ref InstanceProfile
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: inoue-bucket-access-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: inoue-instance-profile
      Roles:
      - !Ref IAMRole
  IAMPolicy:
    Type: 'AWS::IAM::Policy'
    DependsOn:
    - S3
    - IAMRole
    Properties:
      PolicyName: AccessS3bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource: 'arn:aws:s3:::inoue-artifacts'
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource: 'arn:aws:s3:::inoue-artifacts/*'
      Roles:
        - !Ref IAMRole
  S3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: inoue-artifacts
